apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stakater-reloader
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.1.4
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/stakater/reloader
      tag: v1.4.5@sha256:9a45812391fab333acb4fa723f52033477b9b24cab975612b5c7bdf41b93439e

    reloader:
      ignoreNamespaces:
      - flux-system
