apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stakater-reloader
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/stakater/reloader
      tag: v1.4.7@sha256:ea47a3879818820fa0efd59c6ed635c4116b99ec9de040f7995377d0d6766a15

    reloader:
      ignoreNamespaces:
      - flux-system
