apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stakater-reloader
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    reloader:
      ignoreNamespaces:
      - flux-system
