apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stakater-reloader
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/stakater/reloader
      tag: v1.4.0@sha256:751c607948c641fdff933e28bc6c2862086d5980980bb1b0003aae793feeadcd

    reloader:
      ignoreNamespaces:
      - flux-system
