apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wh40k-wiki
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      # Added to keep PVC names aligned in migration app-template v3 to v4
      alwaysAppendIdentifierToResourceName: true

    controllers:
      wiki:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
            envFrom:
              - secretRef:
                  name: wh40k-db-init-secrets
        containers:
          app:
            image:
              repository: requarks/wiki
              tag: 2.5.308@sha256:1eaa2de751c2925871a95a02e0ddbdd5c48bf2e016653b2e4a8f0c646cc4ff83
            env:
              PORT: &port 3000
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: wh40k-wiki-secrets
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      wh40k-wiki:
        controller: wiki
        ports:
          http:
            port: *port

    ingress:
      wh40k-wiki:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: Imperium Maledictum
          hajimari.io/instance: "user,admin"
          hajimari.io/group: "wiki"
          hajimari.io/icon: game-icons:warhammer
        hosts:
          - host: wh40k-wiki.${SECRET_HOST}
            paths:
              - path: /
                service:
                  identifier: wh40k-wiki
                  port: http

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOncePod
        retain: true
        size: 10Gi
        globalMounts:
          - path: /wiki/data
      cache:
        type: emptyDir
        globalMounts:
          - path: /wiki/data/cache
      tmp:
        type: emptyDir
