---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth
  namespace: flux-system
spec:
  targetNamespace: auth
  interval: 10m
  path: ./kubernetes/apps/auth
  dependsOn:
  - name: ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
