---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  targetNamespace: media
  interval: 10m
  path: ./kubernetes/apps/media
  dependsOn:
  - name: postgres-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
