---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/mongodb
  dependsOn:
  - name: cert-manager-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
