---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb
  namespace: flux-system
spec:
  targetNamespace: mongodb
  interval: 10m
  path: ./kubernetes/apps/mongodb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
