---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  targetNamespace: nextcloud
  interval: 10m
  path: ./kubernetes/apps/nextcloud
  dependsOn:
  - name: postgres-cluster
  - name: redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
