---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: productivity
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: productivity
  namespace: flux-system
spec:
  targetNamespace: productivity
  interval: 10m
  path: ./kubernetes/apps/productivity
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
