---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
