---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  targetNamespace: unifi
  interval: 10m
  path: ./kubernetes/apps/unifi
  dependsOn:
  - name: mongodb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
