---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wiki
  namespace: flux-system
spec:
  targetNamespace: wiki
  interval: 10m
  path: ./kubernetes/apps/wiki
  dependsOn:
  - name: postgres-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
