apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      navidrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.54.5@sha256:0648e9772404e29138fe76d1a9dfaebba9c12f7cc20b5ed1bfb3469b0da2c3d3
            env:
              TZ: ${TIMEZONE}
              ND_DATAFOLDER: /data
              ND_MUSICFOLDER: /media/music
              ND_PORT: &port 4533
              ND_SCANSCHEDULE: "12h"
              ND_SESSIONTIMEOUT: "24h"
              ND_LOGLEVEL: "info"
              ND_ENABLETRANSCODINGCONFIG: "false"
              ND_TRANSCODINGCACHESIZE: "512MB"
              ND_ENABLESTARRATING: "false"
              ND_ENABLEFAVOURITES: "false"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: navidrome
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: Music
          hajimari.io/instance: "user,admin"
          hajimari.io/group: "apps"
          hajimari.io/icon: arcticons:virtual-music-player
        hosts:
          - host: music.${SECRET_HOST}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOncePod
        retain: true
        size: 10Gi
      tmp:
        type: emptyDir
      media:
        existingClaim: warp-media-data
        globalMounts:
          - path: /media
            readOnly: true
