apiVersion: v1
kind: Secret
metadata:
    name: media-secrets
    namespace: media
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:QRwLcOziBOXAfpnVZ95GttK6nYnVlHK4xRlkEbn4WaQ=,iv:qWqk/DcMnBYhyP5rQL3ZzK0lQNx0etTUO9PaVSLITkU=,tag:bCbvdbDS8bMehvZ9Punp6w==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ik6w3BnQr3aP641zMPRjmf8PVJacR4G1uz5OiBCUMOs=,iv:kmRt936GGwtA0vY+QdW59L36L1Ws39wyA87+vdITTW4=,tag:CjMC0i6im0zj2+9sX88jwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-db-secrets
    namespace: media
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:k5uTch83ckfULwbQ0+r1L8DwNi66G6gqOt8EEmNu8gc=,iv:BdlRCQKsABFx5g5Nwz2ARFHYX728SSoxT7G+ykPOaDw=,tag:sKOjxWSVG8fh3bVfRpsEtw==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:0S1I8Zygud0TB3hpIKxJnQ==,iv:ZqHYsWWqbb7GK6VmTifYQ/5XOjk68KrVxicIz7BoS9E=,tag:hUfE5vnAPglcqRJ6fmNpxw==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:KfER1w==,iv:JJKUEFSMOGoF942yAvpFyeZO8wk+UoHRDlcTFmly9yg=,tag:4G8R7XMC9tgOKq0jb8Novw==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:zzxcr21dRdw=,iv:P+joEJmUp5SCpHase+vZBzlcgg0Rt35IMrqfMKcaUqI=,tag:VcV3nP5j1VgMBi6goHZDSQ==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:1nTIqVCtKd1+qUwfA4Z1kkDmUJpHen0e6SLrJY0R/Co=,iv:X9J4oeEFqlzgfOhrGxHpQ0RXEq9XtlbwmJtIoAH5igY=,tag:bpFP3OImM4CV/OfINWskpA==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:ZGVZe8N/04E=,iv:1DIfUCnclvpXBd8+zhQHjnCRt9w3yEKQuneJefecJHc=,tag:j773fleIN/P/Zr7OFJAUQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-init-db-secrets
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:96Jt8BxdajA=,iv:LAeupbkVshYP9mMm3+31ssGKUa82+ihBuXXGl3O3Enc=,tag:f4eKSSvghD0+GAMkQ1KInA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:n2lsKXKoisZv9S4e3d4bLg==,iv:2g0HGi/b7yWfiBqGWFvcTiGwF1/+ssoKCW7rxDaSM7I=,tag:SI+w/4ioMbKWZ36QSkHfdw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xkcbdt65R9k=,iv:3B7tV1F1wTs3+PH7UPYyTVcSRdf7+T8oRpcDKU79uLA=,tag:GpbCb+slqoIJCPSCeqpeaA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:fzKmNDvYSLMXYJqEwS8IzZLViSovO4JhoarhY+tN4dQ=,iv:AYELMMaaz9NqJxgDea+XPmhaXk2ZuJ88p1LAbvJXFrY=,tag:rlJbcfxddC3bDEi2JdMufw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kKXOOIEHdgmYOzvf2MhnnjJp3FGl4aWuktEVt7/KNEA=,iv:gtWDZuXX2eTkwsW38rZ4MkSPSiyIm8juLfMFHIhTh98=,tag:CNspasJdNg+zxx1AYdNGaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-db-secrets
    namespace: media
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:x653+J0uaUXo81lJ/gavwy7Lx3T62sTBQ2cFpKsJai8=,iv:2B7MrFQVRcoGqJpsoeYoT7TjlLbQtE4a+CbXTwrcBVc=,tag:pY8/8X4U7t+SCKB3Rfr3+A==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:2k55qCGfcjWn9RKQof2SPg==,iv:5ADtckwj/onczKmhYjUV9aSS3EWLfgZUd3lcDqXjYuk=,tag:/UqKb653to1cRwTss62Kwg==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:u6SYDQ==,iv:M5jLjOZmTiFlPcG9VrCe8WwJqUK7qJ8DPLsWJyu63cI=,tag:vRRsxinf6Aj801QfDPz0MQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:DSAYblAw,iv:KqtELvHW7NMqR5Kz1RD7TqEdpmvq9DncyUvUiKH6lwo=,tag:59YFTyOdOE+rH6pTarL8tg==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:FpPXhHL3YIObCsZF1yZgmEO0s7tMExvRyL6infJRh2o=,iv:IB/KDg6JNlb27b495mrLPxiD9SCJw9tQcvzNXSmrWVs=,tag:KgvH0qg//hQUCEknuUNHSw==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:+5YAOtdD,iv:flvzyY4JIikLQ4baai63n/1R49nE8CjvNqZEU7bUuxA=,tag:ZtLfjmqaokmo0GPoJenmZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-init-db-secrets
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9WFUWZwr,iv:teh1UXZ24gYCZ54VUNj6rDN+VXSA+3xV4UKLypFvWw8=,tag:TgrY9mtaYJ/g+MT/HINkQQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:n2lsKXKoisZv9S4e3d4bLg==,iv:2g0HGi/b7yWfiBqGWFvcTiGwF1/+ssoKCW7rxDaSM7I=,tag:SI+w/4ioMbKWZ36QSkHfdw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:kE+pUO/O,iv:pY80y7WrMi+YFB6zR7BX3tD7hJD5NoU/JUAKfttpRS0=,tag:CsJ8ndMzkcTkR4hBnl8MJg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kbY0mhuoIeWOGiZ0ZLB8vxdP3QUjsMQNnVCskqsTb+s=,iv:qGC4DbsfhL8g51KO0j2zlYihm2NTJQqrO9oi/i6yDpQ=,tag:4H5JJHbMwIssWSyCKnMifQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kKXOOIEHdgmYOzvf2MhnnjJp3FGl4aWuktEVt7/KNEA=,iv:gtWDZuXX2eTkwsW38rZ4MkSPSiyIm8juLfMFHIhTh98=,tag:CNspasJdNg+zxx1AYdNGaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-db-secrets
    namespace: media
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:pzhm84CTOp/h36ufnzElL1VyqG2CWz6LTVwwITcB5Bc=,iv:rnC8KuM76GBjsfHeq2+zuts3my2bXADGnwErIU6lw8w=,tag:aIUod3HJI+fDkJY5W09MMQ==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:c3QJCO5BJsYsLMLI11eHpg==,iv:x2HYsrDWgYGyUIw45yZGFb4FxtlO7LdvjK2svMDeT2I=,tag:m728kwMqyvWXS0FVxY9Acw==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:Owswig==,iv:s66X+xfaX+GICHS9TMmYFdojCmjNHfZxpflX8lq96LY=,tag:qB4kWTA1LJ4gIryn0PLhdw==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:kkKcpMca,iv:IEtgEt+RFMmg/P42TEmDX7++ftzWMU8mtuaaQoRjJ5I=,tag:onEu779yh+tXyqmihOfg7A==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:kwhXEmeU0kPdLYqxD7GXHW4duZ2GTbTS0/S8rEDrmpI=,iv:jKFNPAP8WUnJvKz5wccKRRXF8vWadclA+pBFvbt8VS4=,tag:YfQYFJXm3m7GhU5k7i+DYw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:mYaaxTpm,iv:Ik2JARJ1dxh37s6Rq3+teh5exH43G2QAFxEWhra2Xa8=,tag:IjFs0GjcOCUhHtcdwu2dOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-init-db-secrets
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ozYBxO4z,iv:Ve+fvCIU7dDZo4cWP7pfXguj3n0pcQVZwliooGwUagE=,tag:9hHg9JkTUmNW7rpbb0oB1Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:n2lsKXKoisZv9S4e3d4bLg==,iv:2g0HGi/b7yWfiBqGWFvcTiGwF1/+ssoKCW7rxDaSM7I=,tag:SI+w/4ioMbKWZ36QSkHfdw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ucBVRgSh,iv:ZvGxLtGdWJ2yFEVPJ5NgwXvpDQi2R9v1V+UISVlkw80=,tag:+CgUfN4m9PGWnGFkF+8XUA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:/Lpgd1bFP1ZQzoHybAUR8orVPD9tP7vxrvjw6DAyOpc=,iv:+HCp2a90NA+4oSf+HJl88u/DyXO9ZPmBeVrPk7rKV3E=,tag:IoZiGczGQUWWVz5t6Ts11Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kKXOOIEHdgmYOzvf2MhnnjJp3FGl4aWuktEVt7/KNEA=,iv:gtWDZuXX2eTkwsW38rZ4MkSPSiyIm8juLfMFHIhTh98=,tag:CNspasJdNg+zxx1AYdNGaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bazarr-db-secrets
    namespace: media
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:pad16oEZWWSSglfryZ9uSA==,iv:gaYw9hsT5av0nReJitml21otu/IJril3JeBfqg+2v3k=,tag:9zJGvrSNdf1DjyAZbVEzSw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:+Jnsgw==,iv:XbRWqFza19LViw/KgDcMJvvWCH4yMS/WZMrX+1AT0hQ=,tag:9epUoVfVTGbqQO7dLaEtww==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:7sup5HLY,iv:pYap8XMsGPmio2/tcDe68Z1a1ICvKAJxmdYae3PXqOY=,tag:dXeeVpEQ5nxfI/wgAoofgA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:t1qXHbojfowTlY0C33+I4MeikLbg09EpsX5dC8X/yPM=,iv:TDNVihCxirmlFs5PEiMp75fl7gi88WxCMSIqCsXw3oA=,tag:G8vneSK/oX+9ab3et3V8Lw==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:zj5QZXgJ,iv:iYTaJ+UDAr1xSEI67JfbVD4NIemKBZpK+zs0OM3vPL8=,tag:G2FR3cJesiFhlIDlDV2r/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bazarr-init-db-secrets
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oq2RaqVl,iv:WT268RBv58b5JxttHgcvxKAE2PItICMgZcgT0LMfuxg=,tag:XutjdtNDc3HFwrQ7Ah155Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:n2lsKXKoisZv9S4e3d4bLg==,iv:2g0HGi/b7yWfiBqGWFvcTiGwF1/+ssoKCW7rxDaSM7I=,tag:SI+w/4ioMbKWZ36QSkHfdw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:DGgW4Q/C,iv:MFGLBu9yiC2LPlT43+Zb5imPTvALuoJc2lUEtpgDmEs=,tag:Rb+I+ypMlC4KAcQsooVG7w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VX470AtoBEHdBH0a3Gu/w5Ajc7M2u7QSKa0kw/eRWvM=,iv:nQnfabixCDXNyVgLesK5XQKWRTGP6OnQM/gD+r/NTvc=,tag:Q0fCxYJmzWYmvxRwL50f9Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kKXOOIEHdgmYOzvf2MhnnjJp3FGl4aWuktEVt7/KNEA=,iv:gtWDZuXX2eTkwsW38rZ4MkSPSiyIm8juLfMFHIhTh98=,tag:CNspasJdNg+zxx1AYdNGaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3VYR0pudnVFV1ljWEdS
            M3UyUjIzSHhLclhMS0o3Z0l0M3h0Y3A0SlNzCnJMUWtPREhTZHRIbkp2NE16YnpY
            bGZORHNjRjNXVkdVeEt1eFFYYWNvdncKLS0tIGpXVWxlNHA4VVJwdDNSQVpPRk5C
            cEJYWjZCVnlnSlordU5SODRuc2dTcjAKaD5OT5hy34auAQX1aJvJqjCfsui2KPdr
            lXHffDilXdkb2K3K4q7jjag663kZOF6zwm7h/PztH2McRzWLqQv4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T20:37:03Z"
    mac: ENC[AES256_GCM,data:l5v67wUYYZ4akjyYIeKJgrLLaTd3zgfnvRBniJRmZaT5fItkK0orhPuCR32M+LCfdjwV60DL8IzXblztq5cJU+RYkXCZ3SbuqoAdgitvoalM4u96vUHuGxX4lvrm+609caIqaTswoNh/1Li3Qe3aziDgj3qeaumUQqVySTbdK6c=,iv:f6y5LBvbVXrh0mTxYYejXLxSxC1Q8rwsN2/v+nZvYFo=,tag:YOE0CVtSiPL6CDafGqvHlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
