apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql-with-vectors
  namespace: default
spec:
  images:
    - major: 17
      image: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3@sha256:acebb38ca309938bc05ce268b019c98aa718cb554dd54e4443654d9d00a0d498
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: default
spec:
  images:
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.6-minimal-bookworm@sha256:4cbe79a05ae31043a04c060f50e4694fc932e1c33f7a63e54b9c7487480a481f
