apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
  namespace: postgres
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: main
