---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: ${SECRET_DNS_ZONE}
            solverName: desec-http
            config:
              apiUrl: https://desec.io/api/v1
              domainName: ${SECRET_DNS_ZONE}
              secretName: desec-secret
              secretKeyName: desec-token
        selector:
          dnsZones:
            - ${SECRET_DNS_ZONE}
