---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    solvers:
        - dns01:
            webhook:
              groupName: ${SECRET_DNS_ZONE}
              solverName: desec-http
              config:
                apiUrl: https://desec.io/api/v1
                domainName: ${SECRET_DNS_ZONE}
                secretName: desec-secret
                secretKeyName: desec-token
          selector:
            dnsZones:
              - ${SECRET_DNS_ZONE}
