---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-secret
              key: digitalocean-token
        selector:
          dnsZones:
            - ${SECRET_DNS_ZONE}
