apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-pvc
  namespace: immich
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi # Size does not matter
