apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.8.4
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system

  values:
    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: v1.119.1

    env:
      REDIS_HOSTNAME: redis-master.redis
      REDIS_DBINDEX: 1
      DISABLE_REVERSE_GEOCODING: "false"
      REVERSE_GEOCODING_PRECISION: "2"
      LOG_LEVEL: verbose
      OAUTH_ENABLED: "false"
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: DB_HOSTNAME
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: DB_USERNAME
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: DB_DATABASE_NAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: DB_PASSWORD

    postgresql:
      enabled: false

    immich:
      metrics:
        enabled: false

      persistence:
        library:
          existingClaim: immich-upload-pvc

    server:
      resources:
        requests:
          cpu: 15m
          memory: 512Mi
        limits:
          memory: 2Gi

      initContainers:
        init-db:
          image: ghcr.io/onedr0p/postgres-init:16
          envFrom:
            - secretRef:
                name: immich-db-init-secrets
          volumeMounts:
            - name: db-init
              mountPath: /initdb/

      persistence:
        db-init:
          enabled: true
          type: configMap
          name: db-init

      ingress:
        main:
          enabled: true
          annotations:
            nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            hajimari.io/enable: "true"
            hajimari.io/appName: Photos
            hajimari.io/instance: "user,admin"
            hajimari.io/group: "apps"
            hajimari.io/icon: simple-icons:immich

          hosts:
            - host: "photos.${SECRET_HOST}"
              paths:
                - path: /
                  pathType: Prefix

    machine-learning:
      resources:
        requests:
          cpu: 100m
          memory: 2Gi
        limits:
          memory: 2Gi

      probes:
        liveness:
          enabled: false
          spec:
            initialDelaySeconds: 90
        readiness:
          enabled: false
          spec:
            initialDelaySeconds: 90
        startup:
          enabled: false
          spec:
            initialDelaySeconds: 90
