apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  DB_HOSTNAME: ENC[AES256_GCM,data:cg2DmYHMQ3RHLliwpFbLnA==,iv:rtoIpdkgJY3izsJqFlrxOqLjgpkztKKORRUCSy5NOXI=,tag:BHluVbG5S+W8ECQyCE+68w==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:77nTZLrC,iv:uehwg1soVY9i2QnwpvIfw+dRY/NHQ3G9b38LELFuYaU=,tag:zf25e+hLPtYeEBMvfntk+g==,type:str]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:Wq4gvHaV,iv:uwA/2S7R+GGe+D+6uQfIV9Zf788w95AWRH6JGBE5O3g=,tag:PdJdKzr9p2Khlk6cez5b+A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:qt1l6n+BPdXGKpmwBDtvPfdHGLdEtpFz3vN4NLrTqL8=,iv:hCg6shoNbyjqxZqEVWWgnnWxMzq53SLohFqgr7V+a7k=,tag:apRqFzXHTJRq9Yg0G5ZxLw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSWFxbHlDZkZGRlplaDdx
        UExCdzkxZmg4dW9yZWlHSEJheHUzNFpoU0MwClltY2JPTUU2OHBTUjByaUFUZlpv
        ZmlWSGcxZkN0eHUvTWtxWU4xdU15WG8KLS0tIEpvY09FN05PQXFLaWNDUDV6eGVl
        d3hjanpwUlJwaWxER2FQbUNVMjk3akEK29aXb/jEBTYp0to/gbdhOtA2C4vm+GDB
        VpzoD1FutEwZQcbdsI6HjiCQf/Au1K/VNG9H5oG6/gUPE4GqALxFWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-02T16:01:42Z"
  mac: ENC[AES256_GCM,data:vkdGCGFyYgP9/2c38iv2meFhcZvoC2vzC+cPVg9O/reLv4/MwqZjlxZO6aovg6WWbR3CazyYpPp2aFjFwe1HDkyYWMcX2dUwS7ModARKlvcZGC65a7KsCWEKg92BgkHs0riiN/J9rM2bwlE6qaH1xbqyafUH1CGr0Ffc8tfn+oM=,iv:IVGfnmamZCtNGWRjktpGdAqcM/kHoFcZeGw+mo/WGRU=,tag:Rno5c5p8Kau94h4S2yPKkQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-init-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:KQ00JkQ+,iv:sFPdbkDPgp5BMu6jGWP+ccg+E5hUC/4WT64VGj6esW0=,tag:NHAh9fGuTsJW61cibeYjqQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kueRYBo1Nr9pBHCQ7cjGSQ==,iv:4Zk2bZOU4cY4TAOOcJqpjwXVkZFAB6SeI9OSXOQLCuU=,tag:8hUnoaAR1kRhv3FNDl6D+w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:RauJyGXf,iv:+ItWFI2ZFZjhEpZIA/EA6Nj4sJbbk2i08F+q3jacQQw=,tag:A75g4hgh4/Qybqx2kBmO8Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:WNNDFzuoCbku2DOemckkXhx6OKaZAQ4OmaaQzmhrmrE=,iv:DlhD739VU2o/d7/NnQvFdPuvVvGcp5+O+xNTin7s6xY=,tag:T05KP4VzWj1I+NI6fVWJyw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:trBVMMR9YuLuhmQI9wucthtFe4W4BkrDPjFisXlRu/Q=,iv:BU9EbtdyQ+PKpCbjAYZDGZ+LvK2D75b67LjKC+/Ligk=,tag:+V1JDCpufPlTXvXBAUSjIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSWFxbHlDZkZGRlplaDdx
        UExCdzkxZmg4dW9yZWlHSEJheHUzNFpoU0MwClltY2JPTUU2OHBTUjByaUFUZlpv
        ZmlWSGcxZkN0eHUvTWtxWU4xdU15WG8KLS0tIEpvY09FN05PQXFLaWNDUDV6eGVl
        d3hjanpwUlJwaWxER2FQbUNVMjk3akEK29aXb/jEBTYp0to/gbdhOtA2C4vm+GDB
        VpzoD1FutEwZQcbdsI6HjiCQf/Au1K/VNG9H5oG6/gUPE4GqALxFWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-02T16:01:42Z"
  mac: ENC[AES256_GCM,data:vkdGCGFyYgP9/2c38iv2meFhcZvoC2vzC+cPVg9O/reLv4/MwqZjlxZO6aovg6WWbR3CazyYpPp2aFjFwe1HDkyYWMcX2dUwS7ModARKlvcZGC65a7KsCWEKg92BgkHs0riiN/J9rM2bwlE6qaH1xbqyafUH1CGr0Ffc8tfn+oM=,iv:IVGfnmamZCtNGWRjktpGdAqcM/kHoFcZeGw+mo/WGRU=,tag:Rno5c5p8Kau94h4S2yPKkQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
