---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-pgadmin
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/postgres/pgadmin
  dependsOn:
  - name: postgres-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
