---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari-admin
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    env:
      TZ: "${TIMEZONE}"
    hajimari:
      instanceName: "admin"

      lightTheme: gazette
      darkTheme: blackboard

      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppInfo: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultSearchProvider: DuckDuckGo

      namespaceSelector:
        any: true
      name: "Home"
      title: "Home — Admin"

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Start (admin)"
          hajimari.io/icon: "weather-sunset"
          hajimari.io/instance: "admin"
          hajimari.io/group: "homepages"
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://admin.${SECRET_HOST}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: admin.${SECRET_HOST}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        type: emptyDir

    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"

    resources:
      requests:
        cpu: 15m
        memory: 86M
      limits:
        memory: 86M
