apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-data
  labels:
    app.kubernetes.io/name: hajimari
    app.kubernetes.io/instance: hajimari
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
