apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 19.6.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    auth:
      enabled: false
      sentinel: false

    master:
      resources:
        requests:
          cpu: 15m
          memory: 256Mi
        limits:
          memory: 256Mi

    replica:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 15m
          memory: 128Mi
        limits:
          memory: 128Mi

    sentinal:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
