# Of note: https://github.com/linuxserver/docker-unifi-network-application/issues/29

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: unifi-controller
      app.kubernetes.io/name: unifi-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: unifi-controller
        app.kubernetes.io/name: unifi-controller
    spec:
      serviceAccountName: unifi-controller
      initContainers:
        - name: wait-for-mongodb
          image: alpine
          command:
            - sh
            - -c
            - 'until nslookup mongodb.mongodb.svc.cluster.local; do echo waiting for mongodb; sleep 2; done;'
      containers:
        - name: unifi-controller
          image: linuxserver/unifi-network-application:9.0.114@sha256:13c9251d0cd06dd390f76eee0d6e813e92615357f30a39798430fc4c374182f1
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: ${TIMEZONE}
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: MEM_LIMIT
            value: '1900'
          - name: MEM_STARTUP
            value: '1024'
          - name: MONGO_USER
            value: unifi
          - name: MONGO_HOST
            value: mongodb.mongodb
          - name: MONGO_PORT
            value: '27017'
          - name: MONGO_DBNAME
            value: unifi
          envFrom:
          - secretRef:
              name: unifi-db-secrets
          ports:
          - containerPort: 8080
            protocol: TCP
            name: devicecom
          - containerPort: 8443
            protocol: TCP
            name: webapi
          - containerPort: 8880
            protocol: TCP
            name: httpredirects
          - containerPort: 8843
            protocol: TCP
            name: httpsredirects
          - containerPort: 6789
            protocol: TCP
            name: speedtest
          - containerPort: 10001
            protocol: UDP
            name: apdiscovery
          - containerPort: 3478
            protocol: TCP
            name: stun
          - containerPort: 1900
            protocol: UDP
            name: appdiscovery
          - containerPort: 5514
            protocol: UDP
            name: syslogcapture
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 2Gi
          volumeMounts:
            - mountPath: "/config"
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unifi-controller-data
