apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.6.4
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secrets
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-secrets
    authentik:
      redis:
        host: redis-master.redis
        db: 2
    server:
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17
          envFrom:
            - secretRef:
                name: authentik-init-db-secrets
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
      ingress:
        enabled: true
        hosts:
          - sso.${SECRET_HOST}
        https: false
    # prometheus:
    #   rules:
    #     enabled: true
