apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./authelia.yaml
- ./secrets.yaml
configMapGenerator:
  - name: authelia-config
    namespace: auth
    files:
      - configuration.yaml=./config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
