---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: desec-cert-manager-webhook
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-desec-http
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: irreleph4nt
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  dependsOn:
    - name: cert-manager

  values:
    groupName: ${SECRET_DNS_ZONE}

    image:
      repository: ghcr.io/irreleph4nt/cert-manager-webhook-desec-http
      tag: 1.0.1@sha256:e8e24cef96787210d92d677cc2c840e6aa56872c823cc0b4ead15d8176c63820

    secretName:
    - desec-secret

    podSecurityContext:
      enabled: true
      fsGroup: 41419
    containerSecurityContext:
      enabled: true
      runAsUser: 41419
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 15m
        memory: 200M
      limits:
        cpu: 250m
        memory: 200M
