apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: bitnami-chart-mongodb
    namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    auth:
      enabled: true
      databases:
      - unifi
      - unifi_stat
      usernames:
      - unifi
      - unifi
      passwords:
      - ${MONGODB_PASSWORD_UNIFI}
      - ${MONGODB_PASSWORD_UNIFI}
