apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 30m
  chart:
    spec:
      chart: mongodb
      version: 15.6.19
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    auth:
      enabled: true
      databases:
      - unifi
      - unifi_stat
      usernames:
      - unifi
      - unifi
      passwords:
      - ${MONGODB_PASSWORD_UNIFI}
      - ${MONGODB_PASSWORD_UNIFI}

