apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./cluster-secrets.yaml
- ./cluster-settings.yaml
# Loaders
- ./loaders/auth.yaml
- ./loaders/cert-manager/cert-manager.yaml
- ./loaders/cert-manager/issuers.yaml
- ./loaders/home.yaml
- ./loaders/immich.yaml
- ./loaders/ingress.yaml
- ./loaders/media.yaml
- ./loaders/mongodb.yaml
- ./loaders/nextcloud.yaml
- ./loaders/observability.yaml
- ./loaders/postgres/db.yaml
- ./loaders/postgres/cluster.yaml
- ./loaders/postgres/pgadmin.yaml
- ./loaders/productivity.yaml
- ./loaders/redis.yaml
- ./loaders/unifi.yaml
- ./loaders/wiki.yaml
