---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.49.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    # pgadmin upgrades get stuck on the PV if we use RollingUpdate
    strategy:
      type: Recreate

    existingSecret: pgadmin-secrets

    podAnnotations:
      secret.reloader.stakater.com/reload: pgadmin-secrets,pgadmin-config

    containerSecurityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW

    env:
      email: "${SECRET_ADMIN_EMAIL}"

    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "PostgreSQL"
        hajimari.io/icon: simple-icons:adminer
        hajimari.io/group: Databases
        hajimari.io/instance: "admin"
      hosts:
        - host: "postgres.${SECRET_HOST}"
          paths:
            - path: /
              pathType: Prefix

    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 200Mi

    extraSecretMounts:
      - name: pgadmin-config
        mountPath: /pgadmin4/config_local.py
        subPath: config_local.py
        readOnly: true
        secret: pgadmin-config

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
