apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  creationTimestamp: null
  name: ghcr-image-credentials
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvL2Jnb3RpbmsiOnsidXNlcm5hbWUiOiJiZ290aW5rIiwicGFzc3dvcmQiOiJnaHBfNWxoSE1kT01mOGlFZ2RabVdvUmtpaEN2bEdqZVpFM21lTFlDIiwiZW1haWwiOiJicmFtQGdvdGluay5tZSIsImF1dGgiOiJZbWR2ZEdsdWF6cG5hSEJmTld4b1NFMWtUMDFtT0dsRloyUmFiVmR2VW10cGFFTjJiRWRxWlZwRk0yMWxURmxEIn19fQ==
