apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /srv
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: warp-media
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
