apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./signoz.yaml
- ./gatus/secrets.yaml
- ./gatus/gatus.yaml
configMapGenerator:
  - name: gatus-config
    namespace: observability
    files:
      - config.yaml=./gatus/resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
