apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: signoz
      version: 0.51.0
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    frontend:
      ingress:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: Signoz
          hajimari.io/instance: "admin"
          hajimari.io/group: "system"
          hajimari.io/icon: carbon:cloud-logging
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://signoz.${SECRET_HOST}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
        hosts:
        - host: signoz.${SECRET_HOST}
          paths:
          - path: /
            pathType: ImplementationSpecific
            port: 3301
