---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-db
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/postgres/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
