apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-secret
    namespace: cert-manager
stringData:
    digitalocean-token: ENC[AES256_GCM,data:7DJDluFjAEIig8MUsZPGvRg3mXMWY9oQtVckoUMBFbuiVT5VqWeno48i1mZZMD5NHDoB6r8Quq2c720Kq90QtpRcOmqgSCw=,iv:lV9ceC+zxql2LPp31iDYHkRBXEp76NJckBX7HTEeui0=,tag:ZpPnUjPk9BXHj+k62fJv/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TjVnZVAvUko3RktKWEQ4
            aHZ5aEtyWGJmbkVianovWHR6d09QUk52eVNzClNlSDdhV1k5RW1aV1FKdjFMYVdx
            dmJRNlFIVWVlYUJQZ1lJYXY4Qm9WUTgKLS0tIEZqNk1jYkNLeFA0TTFrVlU1NUkz
            OGFlRkdpbkJDS3BNVENrTVVNd3Nub3MKBvfZeJv+CU8fsd9TxAbmw4IwRU7akwKA
            Ctdi2soNQes0OBjJOuKg4E5dAcVq+f01IJ9kvWjIwa/2JzufbZq9wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-25T20:45:18Z"
    mac: ENC[AES256_GCM,data:VYtlB6rO5wSyLvrNfmmRIYtBAG0UYPZdiZ0PCZCAcD+hHXNU11rylr1kIgWDT8obr1vygKefwvuwvuOzD45gWVuK313Wc5Z1cmwp99ewveULfYHaiVxPlAyu5UFS3rAh9WpywdMhdFJC+CABSsucSwuq9hzUYchcXO5qHEHOhiE=,iv:mgVlMvJ6ftiAm6iT4cDWQMIuTODGgIcZbFFIMC1Yu1E=,tag:qCdW6snHryB9FwPfpKdxuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
