apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-secret
stringData:
  digitalocean-token: ENC[AES256_GCM,data:7DJDluFjAEIig8MUsZPGvRg3mXMWY9oQtVckoUMBFbuiVT5VqWeno48i1mZZMD5NHDoB6r8Quq2c720Kq90QtpRcOmqgSCw=,iv:lV9ceC+zxql2LPp31iDYHkRBXEp76NJckBX7HTEeui0=,tag:ZpPnUjPk9BXHj+k62fJv/g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TjVnZVAvUko3RktKWEQ4
        aHZ5aEtyWGJmbkVianovWHR6d09QUk52eVNzClNlSDdhV1k5RW1aV1FKdjFMYVdx
        dmJRNlFIVWVlYUJQZ1lJYXY4Qm9WUTgKLS0tIEZqNk1jYkNLeFA0TTFrVlU1NUkz
        OGFlRkdpbkJDS3BNVENrTVVNd3Nub3MKBvfZeJv+CU8fsd9TxAbmw4IwRU7akwKA
        Ctdi2soNQes0OBjJOuKg4E5dAcVq+f01IJ9kvWjIwa/2JzufbZq9wQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-02T16:00:53Z"
  mac: ENC[AES256_GCM,data:K4jtcR0W/gj+QpSgajY1A/bo0N5acmTXc9HT4Fl3rGn46WuZIe3XV2FTI71avzbXlvPQI8yIIAdGLN1NBPQLp4FgYvjELXGZOnL5aaxMltIXG1aMbMY5IFRk9eVEGOwPLyDelAN7NUH84gxlzFXvu4YHY55qrXofqRFrDD4y2hg=,iv:2+s+KKL4kFCEbFuArCGfObroFB4DX8PvyihBdXnfR98=,tag:rP5E6tZmhN2d3Yyx0MOBUA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
