apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certitifcate
spec:
  secretName: ingress-certitifcate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '${SECRET_HOST}'
  dnsNames:
    - '${SECRET_HOST}'
    - '*.${SECRET_HOST}'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certitifcate-eu
spec:
  secretName: ingress-certitifcate-eu
  issuerRef:
    name: buypass
    kind: ClusterIssuer
  commonName: '${SECRET_HOST}'
  dnsNames:
    - '${SECRET_HOST}'
    - '*.${SECRET_HOST}'
---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: ingress-certitifcate-staging
# spec:
#   secretName: ingress-certitifcate-staging
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   commonName: '${SECRET_HOST}'
#   dnsNames:
#     - '${SECRET_HOST}'
#     - '*.${SECRET_HOST}'
