---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/home
  dependsOn:
  - name: ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
