---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-helm
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
