apiVersion: v1
kind: Secret
metadata:
    name: gatus-db-secrets
    namespace: observability
stringData:
    GATUS_POSTGRES_DATABASE: ENC[AES256_GCM,data:07TSr/Y=,iv:UEQndKwiTSW8U7W5Qk8JYApxfC38IQcwsC77U7qbkn4=,tag:QvOgd3qKT3YrvYWu9PvJBA==,type:str]
    GATUS_POSTGRES_ADDRESS: ENC[AES256_GCM,data:LVp9GpwUt2JpllnathmwH+Wlm0VD0tVUyQk20VDEyQkwUg==,iv:ZUz9qA3MrVpEppdnZaPz56gHhvtUdgH4rwCdQMxWB+c=,tag:UMphMOCoTALPWUEaBezAXw==,type:str]
    GATUS_POSTGRES_USERNAME: ENC[AES256_GCM,data:wNVtYfQ=,iv:S9E0/AuYDQsBvPQ1FMDhcmWdpAAfgscRkj0G9awW3b8=,tag:k23yLan+QlfBL1JEFUX4qw==,type:str]
    GATUS_POSTGRES_PASSWORD: ENC[AES256_GCM,data:sJLfIPuLPz9X07gYeKtEJKgA/u9ZeiCXdIXyUr9TbBg=,iv:5Ohn6/DuRPVR2MaS4eMaedTI0D891mzK/AQgBOXDmYg=,tag:kcktlT+hG57OWqFPiS/mxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMFhCR2ZIR0lCdnh2Rkl2
            WE5NMDBvYVg0UDM3amZjMnJrTW9XQVluZFJBCktNaitZdkZOVXFNYXdPSGpmZGkr
            bzB1SldOYjVsRUV5U09hSUJ5bnoxOFUKLS0tIEtOQmxpaGU0OERPNXF6K1VlS2lW
            ZEkyaUNVWVMxNitBWVlDOGJUUHhZdmMKXrfEhKqlUVjhgaPbFqM3M8/QaxRr/lks
            01R7M6zbmzKovg1q0mRITdwjUgUF6oEPH0k0pRPjgoETJLmg5oDfQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T18:43:55Z"
    mac: ENC[AES256_GCM,data:Jo/XCK+UNYTeSMYNVEQMSdSB6vcVfsW+2mN2G1WgwScvB64u4yYPUB9SJxjZIYXPlofjEfu5xqmCWfc71OXLufimmjFskR8Byw4DzBlyoDJM/zVN3l+GNfBi7FEF/0XgphOcvT+yJ1FkN9TK2yd5HxUJnR4dp8fCtJus5asi9FE=,iv:AIcEqHETNbOSSQM1pJQKlaexfwsRV0J39pxlzGw2qgs=,tag:htbm4HLUfJ1wF6r0Ga+fqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-init-db-secrets
    namespace: observability
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZYSr5fY=,iv:vrj9Vh/syWazmLVMo7LYSVlk6J33RilvA8i3MJ46eoc=,tag:zDEP8Mx9esBy51djuy9ogQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Sy09jNQ1s11MY+HO8Hni/gyLk8SkwcuL6rnDDjxM2MQzyg==,iv:ELI02ql0ywQRPSfKR0UkNtC8Ytd0kuToMgAu2X1xDX4=,tag:c2qSM7Y8OpoafU/12WiGaA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WmTTmpQ=,iv:18eNPd0KsULG1WZ/8NyJnVCjhYjStuzz2enc6X6wOlo=,tag:AHcF1j1cI6JEalgqPk04xQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:BXHlc4iYVatl/ZcnreK6HhJ1H/rjohFcGrz7XpC+SKM=,iv:wzUq0NpDGq3eVDO+p07kDIbNARNU0uO/X+SVZgQRFZ4=,tag:lucqy84dbCv+by7yqrXViA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:CDaTz3cmbu1NEhtBD+n1R+t/+aJ8cCcnS+QlEAYfrpQ=,iv:h8Git9KPjutmIQDn/RwcmwHqrrODiI8YEGayuMKdBwg=,tag:F2MzXHPw9NTaBlokwv+iig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2e5q8e8uz65qsg2j05kj5lppxg0jakg39cfpqagyly5jcccxeaqrgpkmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMFhCR2ZIR0lCdnh2Rkl2
            WE5NMDBvYVg0UDM3amZjMnJrTW9XQVluZFJBCktNaitZdkZOVXFNYXdPSGpmZGkr
            bzB1SldOYjVsRUV5U09hSUJ5bnoxOFUKLS0tIEtOQmxpaGU0OERPNXF6K1VlS2lW
            ZEkyaUNVWVMxNitBWVlDOGJUUHhZdmMKXrfEhKqlUVjhgaPbFqM3M8/QaxRr/lks
            01R7M6zbmzKovg1q0mRITdwjUgUF6oEPH0k0pRPjgoETJLmg5oDfQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T18:43:55Z"
    mac: ENC[AES256_GCM,data:Jo/XCK+UNYTeSMYNVEQMSdSB6vcVfsW+2mN2G1WgwScvB64u4yYPUB9SJxjZIYXPlofjEfu5xqmCWfc71OXLufimmjFskR8Byw4DzBlyoDJM/zVN3l+GNfBi7FEF/0XgphOcvT+yJ1FkN9TK2yd5HxUJnR4dp8fCtJus5asi9FE=,iv:AIcEqHETNbOSSQM1pJQKlaexfwsRV0J39pxlzGw2qgs=,tag:htbm4HLUfJ1wF6r0Ga+fqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
