---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-desec
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 10m
  path: ./kubernetes/apps/cert-manager/desec
  dependsOn:
  - name: cert-manager-cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
