---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/cert-manager/issuers
  dependsOn:
  - name: cert-manager-cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
