apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certitifcate
  namespace: ingress
spec:
  secretName: ingress-certitifcate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '${SECRET_HOST}'
  dnsNames:
    - '${SECRET_HOST}'
    - '*.${SECRET_HOST}'
